import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";
import { createServiceRoleClient } from '@/utils/supabase/service-role';
import { SystemSettings } from '@/types/internship';
import { ThemeProvider } from '@/components/theme-provider';
import { ThemeUpdater } from '@/components/theme-updater';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

async function getSystemSettings(): Promise<SystemSettings | null> {
  try {
    const supabase = createServiceRoleClient();
    
    const { data: settings, error } = await supabase
      .from('system_settings')
      .select('*')
      .single();

    if (error) {
      console.warn('Failed to load system settings for metadata:', error);
      return null;
    }

    return settings;
  } catch (error) {
    console.warn('Error fetching system settings for metadata:', error);
    return null;
  }
}

export async function generateMetadata(): Promise<Metadata> {
  const systemSettings = await getSystemSettings();
  
  return {
    title: systemSettings?.name || "Create Next App",
    description: systemSettings?.name ? `Login to ${systemSettings.name}` : "Generated by create next app",
    icons: systemSettings?.logo_url ? {
      icon: systemSettings.logo_url,
      shortcut: systemSettings.logo_url,
      apple: systemSettings.logo_url,
    } : undefined,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const systemSettings = await getSystemSettings();
  
  return (
    <html lang="en">
      <head>
        {/* Prevent CSS caching for dynamic theming */}
        <meta httpEquiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
        <meta httpEquiv="Pragma" content="no-cache" />
        <meta httpEquiv="Expires" content="0" />
        
        {systemSettings?.logo_url && (
          <>
            <link rel="icon" href={systemSettings.logo_url} />
            <link rel="shortcut icon" href={systemSettings.logo_url} />
            <link rel="apple-touch-icon" href={systemSettings.logo_url} />
          </>
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider 
          primaryColor={systemSettings?.primary_color} 
          secondaryColor={systemSettings?.secondary_color}
        >
          <ThemeUpdater 
            primaryColor={systemSettings?.primary_color} 
            secondaryColor={systemSettings?.secondary_color}
          />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
